import os

# os.rename('aceSwords.png', 'acePentacles1.png')
# os.rename('twoSwords.png', 'twoPentacles1.png')
# os.rename('threeSwords.png', 'threePentacles1.png')
# os.rename('fourSwords.png', 'fourPentacles1.png')
# os.rename('fiveSwords.png', 'fivePentacles1.png')
# os.rename('sixSwords.png', 'sixPentacles1.png')
# os.rename('sevenSwords.png', 'sevenPentacles1.png')
# os.rename('eightSwords.png', 'eightPentacles1.png')
# os.rename('nineSwords.png', 'ninePentacles1.png')
# os.rename('tenSwords.png', 'tenPentacles1.png')
# os.rename('pageSwords.png', 'pagePentacles1.png')
# os.rename('knightSwords.png', 'knightPentacles1.png')
# os.rename('queenSwords.png', 'queenPentacles1.png')
# os.rename('kingSwords.png', 'kingPentacles1.png')

os.rename('acePentacles1.png', 'acePentacles.png')
os.rename('twoPentacles1.png', 'twoPentacles.png')
os.rename('threePentacles1.png', 'threePentacles.png')
os.rename('fourPentacles1.png', 'fourPentacles.png')
os.rename('fivePentacles1.png', 'fivePentacles.png')
os.rename('sixPentacles1.png', 'sixPentacles.png')
os.rename('sevenPentacles1.png', 'sevenPentacles.png')
os.rename('eightPentacles1.png', 'eightPentacles.png')
os.rename('ninePentacles1.png', 'ninePentacles.png')
os.rename('tenPentacles1.png', 'tenPentacles.png')
os.rename('pagePentacles1.png', 'pagePentacles.png')
os.rename('knightPentacles1.png', 'knightPentacles.png')
os.rename('queenPentacles1.png', 'queenPentacles.png')
os.rename('kingPentacles1.png', 'kingPentacles.png')